### PR TITLE
favicon, about page info tables, links to audits, dex logos

### PR DESCRIPTION
**Pull request by g-a-v-i-n**

### CODE REVIEW

**Comment by willbach** [comment]
I made some changes to `App.scss`, let me know if you have any issues resolving the conflicts

**Comment by g-a-v-i-n** [comment]
Would be great to get this repo transferred so I can work more effectively, otherwise I have to keep changing origins with git.

**Comment by willbach** [comment]
Ok, I just looked this up and it looks like someone in the `urbit` org with permissions to create a repository will have to do the transfer. The simplest method may be to give me permissions temporarily, I'll ask. In the meantime you can add this repo as a different remote with `git remote add willbach https://github.com/willbach/starketplace.git` or the ssh version as appropriate. Then you can just pull from my master with `git pull willbach master`

Relevant docs: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository

**Comment by g-a-v-i-n** [comment]
Ok cool, thanks for looking into it. I'll pull from this master

**Pull request closed without merging**
